version: 2

jobs:
  build:
    docker:
    - image: circleci/golang:1.12

    steps:
    - checkout
    - run: go test -v ./...
    - run: go build -tags netgo -o details ./...
    - persist_to_workspace:
        root: .
        paths:
        - details

  push_image:
    docker:
    - image: circleci/golang

    steps:
    - checkout
    - setup_remote_docker
    - attach_workspace:
        at: .
    - run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD quay.io
    - run: docker build -t quay.io/simonpasquier/go-bookinfo-details:latest .
    - run: docker push quay.io/simonpasquier/go-bookinfo-details


workflows:
  version: 2
  main:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - push_image:
        requires:
        - build
        filters:
          branches:
            only: master
